Create sendEmail form Components
GSG-G11/Taskillo pull request #101
Opened 2022-05-13 17:30 UTC by nada-abuzaid

Relates #53 
Close #53

2022-05-13 17:53 UTC, MaramMs approved these changes

2022-05-14 16:36 UTC, karam-zomlut requested changes

2022-05-14 16:36 UTC, karam-zomlut commented on client/src/App.js
> +      <SendEmail />
Good Job, Nada
I think here you should group all elements front send email in one page ```sendEmailPage``` and call it here.

> Call it from the pages folder

2022-05-14 19:47 UTC, Nizar7zak requested changes
Great Job Nada !!

2022-05-14 19:47 UTC, Nizar7zak commented on client/src/pages/sendEmail/sendEmail.js
> +import 'bootstrap/dist/css/bootstrap.min.css';
you should import bootstrap in App file not here.

2022-05-15 01:19 UTC, AmranElmasri approved these changes

2022-05-15 06:51 UTC, Nizar7zak approved these changes

2022-05-15 06:51 UTC, merged