Create signup form frontend
GSG-G11/Taskillo pull request #102
Opened 2022-05-13 22:03 UTC by MaramMs

![image](https://user-images.githubusercontent.com/48523500/168395009-acb687d5-d838-486f-8d05-dfd24afe947f.png)
Relates #98 
Close #98

2022-05-14 06:14 UTC, nada-abuzaid requested changes

2022-05-14 06:14 UTC, nada-abuzaid commented on client/src/App.css
> +  background-color:black !important;
The background color is not black, and why do you use `!important`? 
```suggestion
  background-color: #1C1C28;
```

2022-05-14 06:14 UTC, nada-abuzaid commented on client/src/App.js
> +import 'bootstrap/dist/css/bootstrap.min.css'
You should import it in the Signup page not here, and put your style in the end
```suggestion
import 'bootstrap/dist/css/bootstrap.min.css'
import './style.css'
```

2022-05-14 06:14 UTC, nada-abuzaid commented on client/src/App.js
> +    <div className="container">
Please, don't delete the general code.
```suggestion
    <div className="App container">
```

2022-05-14 06:14 UTC, nada-abuzaid commented on client/src/pages/signUp.jsx
> +import '../scss/signup.css'
Put your CSS in the the signup folder with signup.jsx file.
```suggestion
import './signup.css'
```

2022-05-14 06:14 UTC, nada-abuzaid commented on client/src/pages/signUp.jsx
> +        <FormField  type='number' name='code' placeholder='Enter  verification code'/>
```suggestion
        <FormField  type='number' name='code' placeholder='Enter verification code'/>
```

2022-05-14 06:14 UTC, nada-abuzaid commented on client/src/components/Form/FormField.jsx
> +        className='form-control  mb-3 w-50 text-white '
Pass the className as a props.
```suggestion
        className={`form-control  ${className} `}
```

2022-05-14 16:37 UTC, karam-zomlut commented
> ![image](https://user-images.githubusercontent.com/48523500/168418797-847b3e90-7c4c-4c98-b8a6-762bd615079f.png)
> 
> Relates #98 Close #98

2022-05-14 19:53 UTC, Nizar7zak requested changes

2022-05-14 19:53 UTC, Nizar7zak commented on client/src/pages/SignUp/signUp.jsx
> +import 'bootstrap/dist/css/bootstrap.min.css'
you should import Bootstrap in App file not here.

2022-05-14 19:53 UTC, Nizar7zak commented on client/src/utils/signUpValidation.js
> +  username:Yup.string().min(3,'Username should be at least 3 char ').max(20,'Username should be at most 20 char ').required('username'),
you should be consistent, so please instead of .required(username)
.required('username is required')

2022-05-15 01:18 UTC, AmranElmasri approved these changes

2022-05-15 08:32 UTC, karam-zomlut approved these changes

2022-05-15 09:18 UTC, Nizar7zak approved these changes

2022-05-15 09:19 UTC, merged