Create Login Form
GSG-G11/Taskillo pull request #103
Opened 2022-05-14 01:20 UTC by AmranElmasri

Relates #100
![Screenshot from 2022-05-14 04-10-46](https://user-images.githubusercontent.com/88728652/168405470-cfe6d645-d3e2-4daf-915b-fdbf827fce67.png)

2022-05-14 07:51 UTC, MaramMs requested changes
Amran, why did you write pure CSS, use bootstrap classes pls.
and I think the input field is different from the Figma design, check it again pls

2022-05-15 01:21 UTC, AmranElmasri commented
> Amran, why did you write pure CSS, use bootstrap classes pls. and I think the input field is different from the Figma design, check it again pls

I did it

2022-05-15 01:24 UTC, AmranElmasri commented
> Amran, why did you write pure CSS, use bootstrap classes pls. and I think the input field is different from the Figma design, check it again pls

I did it

2022-05-15 11:13 UTC, nada-abuzaid approved these changes

2022-05-15 11:14 UTC, merged