Finish Login With Redux
GSG-G11/Taskillo pull request #106
Opened 2022-05-15 13:27 UTC by karam-zomlut

2022-05-16 12:17 UTC, nada-abuzaid approved these changes

2022-05-16 12:29 UTC, Nizar7zak requested changes

2022-05-16 12:29 UTC, Nizar7zak commented on client/src/pages/Login/index.jsx
> +        const token = document.cookie.split('token=')[1];
you should use the functio(getToken) here.

2022-05-16 12:29 UTC, Nizar7zak commented on client/src/pages/SignUp/index.jsx
> +        const token = document.cookie.split('token=')[1];
you should use the functio(getToken) here.

2022-05-16 15:01 UTC, AmranElmasri approved these changes

2022-05-17 19:57 UTC, Nizar7zak approved these changes

2022-05-17 19:58 UTC, merged