Create Login Controller
GSG-G11/Taskillo pull request #38
Opened 2022-04-29 22:24 UTC by AmranElmasri

2022-04-30 14:23 UTC, nada-abuzaid requested changes

2022-04-30 14:23 UTC, nada-abuzaid commented on server/src/controllers/user/login.ts
> +      res.cookie('token', token, { httpOnly: true, secure: true })
Edit the secure value to false

2022-04-30 14:23 UTC, nada-abuzaid commented on server/src/controllers/user/login.ts
> +      err.details.forEach((error) => errorList.push(error.message));
Add Error' type to the error parameter

2022-04-30 16:04 UTC, AmranElmasri commented on server/src/controllers/user/login.ts
> +      res.cookie('token', token, { httpOnly: true, secure: true })
done nada

2022-04-30 16:04 UTC, AmranElmasri commented on server/src/controllers/user/login.ts
> +      err.details.forEach((error) => errorList.push(error.message));
done nada

2022-04-30 23:15 UTC, nada-abuzaid approved these changes

2022-05-01 11:51 UTC, Nizar7zak requested changes

2022-05-01 11:51 UTC, Nizar7zak commented on server/src/controllers/index.ts
> +// eslint-disable-next-line import/prefer-default-export
avoid commented lines, instead you can add this rule to your rules in eslint file.

2022-05-01 11:51 UTC, Nizar7zak commented on server/src/controllers/user/login.ts
> +    const { email, password } = await signInSchema.validateAsync(req.body, { abortEarly: false });
you can add option object {abort early} to the schema file, i think it is better than add it here.

2022-05-01 11:51 UTC, Nizar7zak commented on server/src/controllers/user/login.ts
> +    if (rowCount === 0) {
here you can write a condition like this 
if(!rowCount)

2022-05-01 11:51 UTC, Nizar7zak commented on server/src/controllers/user/login.ts
> +      throw customError('The email does not exist sign up insted', 401);
here you should say you have a problem without explain to the client side if this email have an account or not 
` return res.status(400).json({ message: 'Invalid Email or Password' }); `

2022-05-01 11:51 UTC, Nizar7zak commented on server/src/controllers/user/login.ts
> +      throw customError('please write a correct password', 401);
here you should say you have a problem without explain to the client side if this email have an account or not 
` return res.status(400).json({ message: 'Invalid Email or Password' }); `
 the samething, moreover your status will be 400 not 401

2022-05-01 11:51 UTC, Nizar7zak commented on server/src/controllers/user/login.ts
> +      err.details.forEach((error: Error) => errorList.push(error.message));
I suppose if we present the first error come from validation it's better than this way.

2022-05-03 13:30 UTC, karam-zomlut approved these changes

2022-05-05 12:33 UTC, merged