Handle get projects route
GSG-G11/Taskillo pull request #40
Opened 2022-04-30 08:11 UTC by nada-abuzaid

Relates #39

2022-05-01 11:55 UTC, Nizar7zak requested changes

2022-05-01 11:55 UTC, Nizar7zak commented on server/src/controllers/projects/getProjectsController.ts
> +    if (!rows) return res.status(204).json({ message: 'No data found' });
here, you should check the length of array rows, or take rowCount from your query,
empty array will return true value always!

2022-05-01 13:02 UTC, Nizar7zak approved these changes

2022-05-02 16:55 UTC, AmranElmasri approved these changes

2022-05-03 13:36 UTC, karam-zomlut approved these changes

2022-05-05 11:19 UTC, merged