Handle Add Project Route
GSG-G11/Taskillo pull request #50
Opened 2022-04-30 14:08 UTC by nada-abuzaid

Relates #41

2022-05-01 12:04 UTC, Nizar7zak requested changes
this pull request will be request changes until you can get an id from cookies

2022-05-01 12:04 UTC, Nizar7zak commented on server/src/controllers/projects/addProjectController.ts
> +  // userId from cookies
please, Avoid comments

2022-05-01 12:04 UTC, Nizar7zak commented on server/src/controllers/projects/index.ts
> +// eslint-disable-next-line import/prefer-default-export
again you should add this rule in eslint file

2022-05-01 13:03 UTC, Nizar7zak approved these changes

2022-05-03 12:36 UTC, AmranElmasri approved these changes

2022-05-03 13:41 UTC, karam-zomlut approved these changes

2022-05-05 11:51 UTC, merged