Handle delete task route
GSG-G11/Taskillo pull request #51
Opened 2022-04-30 15:53 UTC by AmranElmasri

relats #49

2022-05-01 12:26 UTC, Nizar7zak requested changes

2022-05-01 12:26 UTC, Nizar7zak commented on server/src/controllers/tasks/deleteTaskController.ts
> +  const { id } = req.body;
you can send your id as params instead of body.

2022-05-01 12:26 UTC, Nizar7zak commented on server/src/controllers/tasks/deleteTaskController.ts
> +    res.status(204).json({ status: 204, message: 'The post deleted successfuly' });
here you shouldn't send status again, you send it by res.status

2022-05-01 14:48 UTC, nada-abuzaid approved these changes

2022-05-03 13:52 UTC, karamzomlot approved these changes

2022-05-05 12:39 UTC, merged