Create Edit Task Route
GSG-G11/Taskillo pull request #63
Opened 2022-05-04 11:55 UTC by AmranElmasri

relats #48

2022-05-07 05:51 UTC, MaramMs approved these changes

2022-05-07 10:47 UTC, nada-abuzaid approved these changes

2022-05-08 06:26 UTC, Nizar7zak requested changes

2022-05-08 06:26 UTC, Nizar7zak commented on server/src/controllers/tasks/editTaskController.ts
> +    const { rows } = await editTaskQuery(+id, name, description, priority, endDate, status);
when we have one or two arguments we pass it like this, but when we have more than two arguments, we should pass them as object.

2022-05-08 06:26 UTC, Nizar7zak commented on server/src/database/quieres/tasks/editTaskQuery.ts
> +  status: string,
I suggest to put all arguments in object, moreover, we can define interface for this object.

2022-05-08 08:44 UTC, karam-zomlut approved these changes

2022-05-08 09:32 UTC, merged