Handle Get Specific Project Route
GSG-G11/Taskillo pull request #64
Opened 2022-05-05 15:30 UTC by nada-abuzaid

Relates #46 
Close #46

2022-05-05 17:55 UTC, AmranElmasri approved these changes

2022-05-08 06:30 UTC, Nizar7zak requested changes

2022-05-08 06:30 UTC, Nizar7zak commented on server/src/controllers/projects/getSpecificProjectController.ts
> +    return res.status(200).json({ data: rows, staff, message: 'Success' });
you should move staff in data object.

2022-05-08 08:44 UTC, karam-zomlut approved these changes

2022-05-08 10:35 UTC, merged