Refactor sections
GSG-G11/Taskillo pull request #77
Opened 2022-05-08 17:44 UTC by karam-zomlut

Finish Sections Refactor 
 

- [x] Rename Files
- [x] Remove Try & Catch from controllers
- [x] Use asyncMiddleware in routes

Relates #73 
Close #73

2022-05-08 17:53 UTC, nada-abuzaid approved these changes
Great Karam!

2022-05-08 17:56 UTC, Nizar7zak requested changes

2022-05-08 17:56 UTC, Nizar7zak commented on server/src/controllers/sections/deleteSection.ts
> +  if (rowCount > 0) {
you can check rowCount, truthy value like this, 
if(rowCount)

2022-05-08 17:56 UTC, Nizar7zak commented on server/src/routes/sectionsRoute.ts
> +sectionsRoute.use(checkAuth);
check auth also has try and catch, so we can wrap our middleware with async-middleware and remove try-catch block

2022-05-08 19:10 UTC, AmranElmasri approved these changes

2022-05-09 06:29 UTC, MaramMs approved these changes

2022-05-09 06:30 UTC, merged