Refactor projects
GSG-G11/Taskillo pull request #78
Opened 2022-05-08 17:46 UTC by nada-abuzaid

Relates #74 
Close #74

2022-05-08 17:58 UTC, Nizar7zak requested changes

2022-05-08 17:58 UTC, Nizar7zak commented on server/src/controllers/projects/editProject.ts
> +  const { rows } = await editProjectQuery(projectId, name, description);
we should pass all arguments here in one as object.

2022-05-08 17:58 UTC, Nizar7zak commented on server/src/routes/projectsRoute.ts
>  projectsRoute.use(checkAuth);
check auth also has try and catch, so we can wrap our middleware with async-middleware and remove try-catch block

2022-05-08 18:21 UTC, karam-zomlut approved these changes

2022-05-08 20:31 UTC, AmranElmasri approved these changes

2022-05-09 06:29 UTC, MaramMs approved these changes

2022-05-09 06:30 UTC, merged