refactor user folder
GSG-G11/Taskillo pull request #80
Opened 2022-05-08 18:01 UTC by AmranElmasri

relats #75

2022-05-08 18:14 UTC, Nizar7zak requested changes

2022-05-08 18:14 UTC, Nizar7zak commented on server/src/controllers/user/login.ts
> +    next(new Error());
here, you can send a response to the client side,
return res.status(4xx).json({message:' something'})

2022-05-08 18:14 UTC, Nizar7zak commented on server/src/controllers/user/signUp.ts
> +      .json({ msg: ' Account created successfully' });
be consistent please, we send a message in json object not msg

2022-05-08 18:14 UTC, Nizar7zak commented on server/src/controllers/user/signUp.ts
> +    next(new Error());
what the error here?

2022-05-08 18:18 UTC, AmranElmasri commented on server/src/controllers/user/signUp.ts
> +    next(new Error());
Invalid verification code

2022-05-08 18:24 UTC, nada-abuzaid requested changes
Great Amran!

2022-05-08 18:24 UTC, nada-abuzaid commented on server/src/routes/index.ts
>  import { sendEmailController } from '../controllers';
Remove sendEmailController because we move it to user routes.

2022-05-08 18:24 UTC, nada-abuzaid commented on server/src/controllers/user/sendEmail.ts
> +
please remove the white spaces here (Line 7 & 9)

2022-05-08 18:46 UTC, nada-abuzaid approved these changes

2022-05-08 19:05 UTC, karam-zomlut approved these changes

2022-05-09 06:29 UTC, MaramMs approved these changes

2022-05-09 06:41 UTC, merged